### PR TITLE
Adds link to Codesplain proper

### LINKED ISSUE #29: Add link to main Codesplain app in embedded

### PR DESCRIPTION
**Pull request by dane-johnson**
Links open in new tab with proper XSS prevention

Closes #29

screen shot 2017-05-01 at 10 17 39 am

### CODE REVIEW

**Comment by smokinGun** [comment]
XSS prevention is great ... why are your choosing to make it a button, rather than just a normal link in a webpage where the title appears blue?

**Comment by dane-johnson** [comment]
Cus that'd look ugly as a title

**Comment by smokinGun** [comment]
Fair. Have you tried a white fill-in for the button instead of blue? That way the title will just appear to be raised.

**Comment by Hopding** [comment]
Not a huge fan of that title background. I think an underline might look better. But, I'm not sure that the title's styling really should change at all. 

I would be interested in seeing what it looks like within RuneStone too, since it will take on other CSS properties in that context.

**Comment by dane-johnson** [comment]
If it doesn't change the user won't know to click it. I think the title shouldn't really be the link anyhow.

**Comment by smokinGun** [comment]
Why not just add a separate [smaller] "visit codesplain" button to the page?

**Comment by Hopding** [comment]
I think Jordan might be on the right track. I suppose it isn't obvious that the title can be clicked, and there aren't many styling changes that would indicate that while still looking good. A small blue-text link somewhere might look better.

**Comment by dane-johnson** [comment]
screen shot 2017-05-02 at 10 15 32 am

**Review by Hopding — APPROVED** [review]
Much better. I think it would look better if you kept the link a consistent light blue color (e.g. no underline, and no color change after being visited).

**Comment by dane-johnson** [comment]
I'll leave it natively styled, that way it will inherit the client css.

**Comment by Hopding** [comment]
Are we good to merge this?

**Review by thebho — APPROVED** [review]

**Pull request merged**
